version: '3.8'

services:
  frontend:
    container_name: frontend-nba
    image: frontend
    restart: on-failure
    build:
      context: ./frontend
    volumes: 
     - ./frontend:/usr/src/app
     - /usr/src/app/node_modules
    ports:
     - "3000:3000"
     - "24678:24678"
  backend:
    container_name: backend-nba
    build:
      context: ./backend
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8004:8000"
